apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-service
  namespace: kafka-lab
spec:
  replicas: 2
  selector:
    matchLabels:
      app: email-service
  template:
    metadata:
      labels:
        app: email-service
    spec:
      containers:
        - name: email-service
          image: kafka-email-service:dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8001
          env:
            - name: KAFKA_ENABLED
              value: "true"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
            - name: KAFKA_ORDER_CREATED_TOPIC
              value: orders.created
            - name: KAFKA_AUTO_OFFSET_RESET
              value: earliest
            - name: EMAIL_PROVIDER_API_DELAY_SECONDS
              value: "0.12"
            - name: RESEND_API_KEY
              value: "re_TtXmVUJb_EJiDBZkqjq7RLrBTiNSRdNom"
            - name: REDIS_ENABLED
              value: "false"
            - name: REDIS_PREFER_CACHE
              value: "true"
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: email-service
  namespace: kafka-lab
spec:
  selector:
    app: email-service
  ports:
    - name: http
      port: 8001
      targetPort: 8001
