resources:
  - namespace.yaml
  - kafka.yaml
  - redis.yaml
  - redpanda-console.yaml
  - order-service.yaml
  - email-service.yaml
  - inventory-service.yaml
  - load-orchestrator.yaml
  - observability.yaml
  - hpa.yaml
  - keda.yaml
